### ISSUE TITLE
a to-do list

### ISSUE THREAD

**Issue by LichKing112** [PixelBedrock/PixelBE-Website#2]
### ⇁ Performance
- [x] Better CSS Reset. 
- [ ] Load Stylesheets/Scripts Locally. (CDNs)
- [ ] SE Optimizations.
- [ ] Clean code.

### ⇁ Features
- [x] Page Pre-loader.
- [x] Animations on Scroll. (AOS)
- [ ] Font & Colors Upgrade.
- [ ] Rework Navigation Bar & Footer.
- [ ] Desktop friendly design.

### ⇁ Postponed
- Minecraft server status frame.
- Regulations & Rules page.
- Privacy & Policy page.
